config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"

  # public ルーティング
  scope module: :public do
    get "homes/about" => "homes#about"
    resource :customers, only: [:show, :edit, :update] do
      collection do
        get 'check'
        patch 'withdrawal'
        get 'favorites'
        get 'comments'
      end
    end

    get "places/search", to: "places#search", as: "places_search"
    get "places/detailed_search", to: "places#detailed_search", as: "places_detailed_search"

    resources :playgrounds, only: [:create, :show]

    resources :posts, only: [:index, :show, :edit, :update, :new, :create, :destroy] do
      resources :post_comments, only: [:create, :destroy, :edit, :update]
      resource :post_favorites, only: [:create, :destroy]
    end
  end

  # admin ルーティング
  namespace :admin do
    get "homes/top" => "homes#top"
    resources :tags, except: [:show, :new]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
    resources :post_comments, only: [:index, :destroy]
  end

  # devise customer ルーティング
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_scope :customer do
    post "public/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # devise admin ルーティング
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :post_favorites, dependent: :destroy
  has_many :post_favorite_posts, through: :post_favorites, source: :customer

  validates :name, presence: true
  validates :nickname, presence: true
  validates :encrypted_password, presence: true

  has_one_attached :profile_image

def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join("app/assets/images/no_image32.png")
    profile_image.attach(io: File.open(file_path), filename: "default-image.png", content_type: ["image/png", "image/jpeg"])
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end

  # ゲストログイン用
  def self.guest
    find_or_create_by!(email: "guest@example.com") do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "ゲストユーザー"
      customer.nickname = "ゲストユーザー"
      customer.is_hidden = true
    end
  end

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  # 日別の登録数を集計するスコープ
  scope :group_by_day_customer_count, -> {
    start_date = 30.days.ago.to_date
    end_date = Date.today
    counts = group("DATE(created_at)").count.transform_keys { |date| date.to_date }
    date_range = (start_date..end_date).to_a
    filled_counts = date_range.index_with { |date| counts[date] || 0 }
    filled_counts
  }

  # 月別の登録数を集計するスコープ
  scope :group_by_month_customer_count, -> {
    start_date = Date.today - 11.months
    end_date = Date.today.end_of_month
    if Rails.env == "production"
      counts = group("DATE_FORMAT(created_at, '%Y-%m')").count
    else
      counts = group("strftime('%Y-%m', created_at)").count
    end
    date_range = (start_date..end_date).map { |date| date.strftime("%Y-%m") }
    filled_counts = date_range.index_with { |date| counts[date] || 0 }
    filled_counts
  }

  # ransack検索カラムのアソシエーション
  def self.ransackable_associations(auth_object = nil)
    ["post_comments", "post_favorite_posts", "post_favorites", "posts"]
  end
  # ransack検索するカラム
  def self.ransackable_attributes(auth_object = nil)
    ["name", "nickname", "email", "created_at", "is_hidden", "is_deleted"]
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_customer, only: [:show, :edit, :update]


  def index
    @q = Customer.ransack(params[:q])
    @customers = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def show
  end

  def edit
  end

  def update
    if @customer.update(customer_params)
      flash[:success] = "#{@customer.name}さんの会員情報が更新されました。"
      redirect_to admin_customer_path(params[:id])
    else
      flash.now[:warning] = "未記入項目があります"
      render :edit
    end
  end

  private
    def customer_params
      params.require(:customer).permit(:name, :nickname, :profile_image, :email, :is_deleted, :is_hidden)
    end

    def set_customer
      @customer = Customer.find(params[:id])
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="col-sm-12 col-md-11 col-lg-10 col-xl-8 mx-auto">
  <h1><%= @customer.name %>さんの会員情報編集</h1>
  <%= form_with model: @customer, url: admin_customer_path do |f| %>
    <form>
      <div class="form-group row ml-3 mb-2">
        <label class="col-md-3 col-form-label">会員ID</label>
        <div class="col-md-9 form-row y-middle">
          <div class="col-md-4 d-flex align-items-center">
            <%= content_tag :div, @customer.id %>
          </div>
        </div>
      </div>
      
      <div class="form-group row ml-3 mb-2">
        <label class="col-md-3 col-form-label">プロフィール画像</label>
        <div class="col-md-9 form-row">
          <div class="col-md-8 mr-md-5 d-flex align-items-center">
            <%= f.file_field :profile_image, class: "form-control-file" %>
            <%= render "layouts/error", model: f, attribute: :profile_image %>
          </div>
        </div>
      </div>
    
      <div class="form-group row ml-3 mb-2">
        <label class="col-md-3 col-form-label">氏名</label>
        <div class="col-md-9 form-row">
          <div class="col-md-8 mr-md-5">
            <%= f.text_field :name, class: "form-control" %>
            <%= render "layouts/error", model: f, attribute: :name %>
          </div>
        </div>
      </div>

      <div class="form-group row ml-3 mb-2">
        <label class="col-md-3 col-form-label">ニックネーム</label>
        <div class="col-md-9 form-row">
          <div class="col-md-8 mr-md-5">
            <%= f.text_field :nickname, class: "form-control" %>
            <%= render "layouts/error", model: f, attribute: :nickname %>
          </div>
        </div>
      </div>

      <div class="form-group row ml-3 mb-2">
        <label class="col-md-3 col-form-label">メールアドレス</label>
          <div class="col-md-9 form-row y-middle">
            <div class="col-md-4 d-flex align-items-center">
              <%= content_tag :div, @customer.email %>
            </div>
          </div>
      </div>
      
      <div class="form-group row ml-3 mb-2">
        <label class="col-md-3 col-form-label">公開設定</label>
        <div class="col-md-9 form-row y-middle">
          <div class="col-5  d-flex align-items-center">
            <%= f.radio_button :is_hidden, false %>
            <%= f.label :is_hidden, "公開", value: false, class: "my-0 mr-3" %>
            <%= f.radio_button :is_hidden, true %>
            <%= f.label :is_hidden, "非公開", value: true, class: "m-0" %>
          </div>
        </div>
      </div>

      <div class="form-group row ml-3 mb-2">
        <label class="col-md-3 col-form-label">会員ステータス</label>
        <div class="col-md-9 form-row y-middle">
          <div class="col-5  d-flex align-items-center">
            <%= f.radio_button :is_deleted, false %>
            <%= f.label :is_deleted, "有効", value: false, class: "my-0 mr-3" %>
            <%= f.radio_button :is_deleted, true %>
            <%= f.label :is_deleted, "退会", value: true, class: "m-0" %>
          </div>
        </div>
      </div>
      
      <div class="form-group row ml-3">
        <label class="col-md-3 col-form-label"></label>
        <div class="col-md-9 form-row">
          <div class="col-5">
            <%= f.submit "変更を保存", class: "btn btn-green px-4" %>
          </div>
        </div>
      </div>
      
    </form>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="mx-auto col-12">
  <div class="d-flex justify-content-between">
    <h1>会員一覧</h1>
    <%= search_form_for @q, url: admin_customers_path do |f| %>
      <div class="d-flex">
        <%= f.search_field :name_or_email_or_nickname_cont, class: 'admin-ransack-search form-control mr-2', placeholder: '名前,ニックネーム,メール' %>
        <button class="admin-search-btn btn btn-outline-green mr-3" type="submit" >
           <i class="fa-solid fa-magnifying-glass">検索</i>
        </button>
        <select class="custom-select admin-keyword-sort" id="sort_by" onChange="location.href=value;">
          <option value="">並び替え</option>
          <option value="<%= sort_by_sort_url(sort_url(@q, :created_at), 'created_at+desc') %>">新しい会員</option>
          <option value="<%= sort_by_sort_url(sort_url(@q, :created_at), 'created_at+ask') %>">古い会員</option>
          <option value="<%= sort_by_sort_url(sort_url(@q, :created_at), 'is_hidden+ask') %>">投稿公開</option>
          <option value="<%= sort_by_sort_url(sort_url(@q, :created_at), 'is_hidden+desc') %>">投稿非公開</option>
          <option value="<%= sort_by_sort_url(sort_url(@q, :created_at), 'is_deleted+ask') %>">活動中会員</option>
          <option value="<%= sort_by_sort_url(sort_url(@q, :created_at), 'is_deleted+desc') %>">退会会員</option>
        </select>
      </div>
    <% end %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th class="bg-light"><%= sort_link(@q, :created_at, "会員ID") %></th>
        <th class="bg-light"><%= sort_link(@q, :name, "氏名") %></th>
        <th class="bg-light">メールアドレス</th>
        <th class="bg-light"><%= sort_link(@q, :is_hidden, "公開設定") %></th>
        <th class="bg-light"><%= sort_link(@q, :is_deleted, "ステータス") %></th>
        <th class="bg-light">投稿数</th>
        <th class="bg-light"></th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.id, admin_customer_path(customer), class: "text-dark" %></td>
        <td><%= link_to customer.name, admin_customer_path(customer), class: "text-dark" %></td>
        <td><%= link_to customer.email, admin_customer_path(customer), class: "text-dark" %></td>
        <td style="<%= customer.is_hidden == false ? 'color: #89CA25;' : 'color: #6c757d;' %>">
          <strong class="status"><%= customer.is_hidden == false ? '公開' : '非公開' %></strong>
        </td>
        <td style="<%= customer.is_deleted == false ? 'color: #89CA25;' : 'color: #6c757d;' %>">
          <strong class="status"><%= customer.is_deleted == false ? '有効' : '退会' %></strong>
        </td>
        <td><%= customer.posts.count %></td>
         <td>
          <%= link_to admin_customer_path(customer), class: "text-info" do %>
            <i class="fa-solid fa-file-pen blue"></i>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <div>
    <%= paginate @customers, theme: 'bootstrap-5' %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="col-11 mx-auto">
  <h1><%=  @customer.name %>さんの会員詳細</h1>
  <div class="row">
    <div class="col-7 pr-0">
      <table class="table table-borderless">
        <tr>
          <th>会員ID</th>
          <td class="px-0"><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td class="px-0"><%= @customer.name %></td>
        </tr>
        <tr>
          <th>ニックネーム</th>
          <td class="px-0"><%= @customer.nickname %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td class="px-0"><%= @customer.email %></td>
        </tr>
        <tr>
          <th>公開設定</th>
          <td class="px-0" style="<%= @customer.is_hidden == false ? 'color: #89CA25;' : 'color: #6c757d;' %>">
            <strong class="status"><%= @customer.is_hidden == false ? '公開' : '非公開' %></strong>
          </td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td class="px-0" style="<%= @customer.is_deleted == false ? 'color: #89CA25;' : 'color: #6c757d;' %>">
            <strong class="status"><%= @customer.is_deleted == false ? '有効' : '退会' %></strong>
          </td>
        </tr>
        <tr>
          <th>投稿数</th>
          <td class="px-0"><%= @customer.posts.count %></td>
        </tr>
        <tr>
          <th>作成日</th>
          <td class="px-0"><%= @customer.created_at.strftime("%Y年%m月%d日") %></td>
        </tr>
        <th></th>
        <td class="px-0">
          <%= link_to admin_posts_path(customer_id: @customer.id), class: "btn btn-blue btn-sm px-4 mr-2" do %>
            <i class="fa-solid fa-file-pen"> 投稿一覧を見る</i>
          <% end %>
          <%= link_to admin_post_comments_path(customer_id: @customer.id), class: "btn btn-blue btn-sm px-4 mt-2 mt-xl-0" do %>
            <i class="fa-solid fa-file-pen"> コメント一覧を見る</i>
          <% end %></br>
          <%= link_to edit_admin_customer_path(@customer), class: "btn btn-green btn-sm px-4 mt-2" do %>
            <i class="fa-solid fa-pen-to-square"> 編集する</i>
          <% end %>
        </td>
      </table>
    </div>
      
    <div class="col-5 px-0" style="height: 400px; width: 100%;">
      <%= image_tag @customer.get_profile_image(200,280), class: "profile_image" %>
    </div>
  </div>
</div>