config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"

  # public ルーティング
  scope module: :public do
    get "homes/about" => "homes#about"
    resource :customers, only: [:show, :edit, :update] do
      collection do
        get 'check'
        patch 'withdrawal'
        get 'favorites'
        get 'comments'
      end
    end

    get "places/search", to: "places#search", as: "places_search"
    get "places/detailed_search", to: "places#detailed_search", as: "places_detailed_search"

    resources :playgrounds, only: [:create, :show]

    resources :posts, only: [:index, :show, :edit, :update, :new, :create, :destroy] do
      resources :post_comments, only: [:create, :destroy, :edit, :update]
      resource :post_favorites, only: [:create, :destroy]
    end
  end

  # admin ルーティング
  namespace :admin do
    get "homes/top" => "homes#top"
    resources :tags, except: [:show, :new]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
    resources :post_comments, only: [:index, :destroy]
  end

  # devise customer ルーティング
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_scope :customer do
    post "public/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # devise admin ルーティング
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :customer
  belongs_to :post

  validates :comment, presence: true

  # ransack検索カラムのアソシエーション
  def self.ransackable_associations(auth_object = nil)
    ["customer", "post"]
  end

  # ransack検索するカラム
  def self.ransackable_attributes(auth_object = nil)
    ["comment", "created_at", "post_id"]
  end
end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < ApplicationController
  before_action :authenticate_admin!

  def index
    if params[:customer_id]
      @customer = Customer.find(params[:customer_id])
      @q = @customer.post_comments.ransack(params[:q])
      @post_comments = @q.result(distinct: true).page(params[:page]).per(10)
    elsif params[:post_id]
      @post = Post.find(params[:post_id])
      @q = @post.post_comments.ransack(params[:q])
      @post_comments = @q.result(distinct: true).page(params[:page]).per(10)
    else
      @q = PostComment.ransack(params[:q])
      @post_comments = @q.result(distinct: true).page(params[:page]).per(10)
    end
  end

  def destroy
    PostComment.find(params[:id]).destroy
    flash[:error] = "コメントが削除されました"
    redirect_to request.referer
  end

  private
    def post_comment_params
      params.require(:post_comment).permit(:comment)
    end
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/views/admin/post_comments/index.html.erb
<div class="mx-auto col-12">
  <h1 class="mb-3">
    <% if @customer %>
      <%= "#{@customer.name}さんのコメント一覧" %>
    <% elsif @post %>
      <%= "投稿ID「#{@post.id}」のコメント一覧" %>
    <% else %>
      コメント一覧
    <% end %>
  </h1>
  <div class="d-flex justify-content-end my-1">
    <%= search_form_for @q, url: admin_post_comments_path do |f| %>
      <div class="d-flex">
        <% unless @customer.present? %>
          <%= f.search_field :comment_or_customer_name_cont, class: 'admin-ransack-search form-control mr-2', placeholder: '名前,コメント' %>
          <button class="admin-search-btn btn btn-outline-green mr-3" type="submit">
            <i class="fa-solid fa-magnifying-glass">検索</i>
          </button>
        <% end %>
        <select class="custom-select admin-keyword-sort" id="sort_by" onChange="location.href=value;">
          <option value="">並び替え</option>
          <option value="<%= sort_by_sort_url(sort_url(@q, :created_at), 'created_at+desc') %>">新しいコメント</option>
          <option value="<%= sort_by_sort_url(sort_url(@q, :created_at), 'created_at+ask') %>">古いコメント</option>
        </select>
      </div>
    <% end %>
  </div>
  
  <table class="table">
    <thead>
      <tr>
        <th class="bg-light" style="width: 9%;"><%= sort_link(@q, :created_at, "コメントID",class:"text-dark") %></th>
        <th class="bg-light" style="width: 9%;"><%= sort_link(@q, :post_id, "投稿ID",class:"text-dark") %></th>
        <th class="bg-light" style="width: 15%;"><%= sort_link(@q, :customer_name, "投稿者",class:"text-dark") %></th>
        <th class="bg-light" style="width: 30%;"><%= sort_link(@q, :comment, "コメント",class:"text-dark") %></th>
        <th class="bg-light" style="width: 12%;"><%= sort_link(@q, :created_at, "作成日",class:"text-dark") %></th>
        <th class="bg-light" style="width: 2%;"></th>
      </tr>
    </thead>
    <tbody>
      <% @post_comments.each do |post_comment| %>
      <tr>
        <td><%= post_comment.id %></td>
        <td><%= link_to post_comment.post_id, admin_post_path(post_comment.post), class: "text-dark" %></td>
        <td><%= link_to post_comment.customer.name, admin_customer_path(post_comment.customer), class: "text-dark" %></td>
        <td><%= post_comment.comment %></td>
        <td><%= post_comment.created_at.strftime("%Y年%m月%d日") %></td>
        <td>
          <%= link_to admin_post_comment_path(post_comment), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "red" do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <div>
    <%= paginate @post_comments, theme: 'bootstrap-5' %>
  </div>
</div>