config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"

  # public ルーティング
  scope module: :public do
    get "homes/about" => "homes#about"
    resource :customers, only: [:show, :edit, :update] do
      collection do
        get 'check'
        patch 'withdrawal'
        get 'favorites'
        get 'comments'
      end
    end

    get "places/search", to: "places#search", as: "places_search"
    get "places/detailed_search", to: "places#detailed_search", as: "places_detailed_search"

    resources :playgrounds, only: [:create, :show]

    resources :posts, only: [:index, :show, :edit, :update, :new, :create, :destroy] do
      resources :post_comments, only: [:create, :destroy, :edit, :update]
      resource :post_favorites, only: [:create, :destroy]
    end
  end

  # admin ルーティング
  namespace :admin do
    get "homes/top" => "homes#top"
    resources :tags, except: [:show, :new]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
    resources :post_comments, only: [:index, :destroy]
  end

  # devise customer ルーティング
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_scope :customer do
    post "public/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # devise admin ルーティング
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
end

app/views/places/_search_results.html.erb
<% if places.present? %>
  <div class="row">
    <% places.each do |place| %>
      <%= link_to places_detailed_search_path(place_id: place.place_id), class: 'text-dark places' do %>
        <ul class="list-group">
          <li class="list-group-item d-flex places">
            <div class="mr-3">
              <% if place.photos.present? %>
                <% place.photos.each do |photo| %>
                  <% photo_url = "https://maps.googleapis.com/maps/api/place/photo?maxwidth=300&photoreference=#{photo.photo_reference}&key=#{ENV['GOOGLE_API_KEY']}" %>
                  <img src="<%= photo_url %>" alt="写真" width="210" height="140">
                <% end %>
              <% else %>
                <img src="/assets/no_image32.png" width="210" height="140">
              <% end %>
            </div>
            <div>
              <h4><%= place.name %></h4>
              
              <% if place.formatted_address.present? %>
                <p><%= place.formatted_address %></p>
              <% else %>
              <% end %>
              
              <% if place.vicinity.present? %>
                <p><%= place.vicinity %></p>
              <% else %>
              <% end %>
  
              <% if place.rating.present? %>
                <p>Google評価: <%= place.rating %></p>
              <% else %>
                <p>Google評価: なし</p>
              <% end %>
            </div>
          </li>
        </ul>
      <% end %>
    <% end %>
  </div>
<% else %>
  <p>検索結果がありません。</p>
<% end %>

app/views/places/detailed_search.html.erb
<h2>詳細検索結果</h2>

<div>
  <h4><img src="<%= @place.icon %>" alt="アイコン" width="40" height="40"> <%= @place.name %></h4>
  
  <% if @place.json_result_object["editorial_summary"].present? %>
    <% summary = @place.json_result_object["editorial_summary"] %>
    <% if summary["overview"].present? %>
      <p><%= summary["overview"] %></p>
    <% end %>
  <% end %>

  <p>住所:</p>〒<%= @place.postal_code %>
  <% province = ""
     @place.address_components.each do |component|
       if component["types"].include?("administrative_area_level_1")
         province = component["long_name"]
       end
     end %>
  
  <p><%= province + @place.vicinity %></p>


  <% if @place.rating.present? %>
    <p>Google評価: <%= @place.rating %></p>
  <% else %>
    <p>Google評価: なし</p>
  <% end %>

  <% if @place.opening_hours.present? && @place.opening_hours.is_a?(Hash) %>
    <h5>営業時間</h5>
    <% if @place.opening_hours["open_now"] %>
      <p>現在営業中</p>
    <% else %>
      <p>現在営業していません</p>
    <% end %>
    <ul>
      <% @place.opening_hours["weekday_text"].each do |weekday| %>
        <li class="list-inline"><%= weekday %></li>
      <% end %>
    </ul>
  <% end %>


  <% if @place.website.present? %>
    <p>公式ウェブサイト: <a href="<%= @place.website %>"><%= @place.website %></a></p>
  <% end %>

  <% if @place.international_phone_number.present? %>
    <p>電話番号: <%= @place.international_phone_number %></p>
  <% end %>

  <% if @place.photos.present? %>
    <% @place.photos.each do |photo| %>
      <% photo_url = "https://maps.googleapis.com/maps/api/place/photo?maxwidth=300&photoreference=#{photo.photo_reference}&key=#{ENV['GOOGLE_API_KEY']}" %>
      <img src="<%= photo_url %>" alt="写真" width="180" height="120">
    <% end %>
  <% else %>
    <img src="/assets/no_image32.png" width="180" height="120">
  <% end %>
  
  <% if @place.json_result_object["geometry"].present? %>
    <% location = @place.json_result_object["geometry"]["location"] %>
    <% latitude = location["lat"] %>
    <% longitude = location["lng"] %>
  <% end %>

  <% if customer_signed_in? %>
    <%= form_with model: Playground.new, url: playgrounds_path, method: :post, local: true do |f| %>
      <%= f.hidden_field :place_id, value: @place.place_id if @place.place_id.present? %>
      <%= f.hidden_field :latitude, value: latitude if latitude.present? %>
      <%= f.hidden_field :longitude, value: longitude if longitude.present? %>
      <%= f.hidden_field :name, value: @place.name  if @place.name.present? %>
      <%= f.hidden_field :overview, value: summary["overview"] if summary.present? %>
      <%= f.hidden_field :icon, value: @place.icon if @place.icon.present? %>
      <%= f.hidden_field :postal_code, value: @place.postal_code if @place.postal_code.present? %>
      <%= f.hidden_field :address, value: @place.vicinity if @place.vicinity.present? %>
      <%= f.hidden_field :prefecture, value: province if province.present? %>
      <%= f.hidden_field :rate, value: @place.rating if @place.rating.present? %>
      <%= f.hidden_field :open_now, value: @place.opening_hours["open_now"] if @place.opening_hours.present? %>
      <%= f.hidden_field :business_hours, value: @place.opening_hours["weekday_text"].to_json if @place.opening_hours.present?%>
      <%= f.hidden_field :website, value: @place.website if @place.website.present? %>
      <%= f.hidden_field :phone_number, value: @place.international_phone_number if @place.international_phone_number.present? %>
      <%= f.hidden_field :photo_url, value: @place.photos.first&.photo_reference.present? ? "https://maps.googleapis.com/maps/api/place/photo?maxwidth=300&photoreference=#{@place.photos.first.photo_reference}&key=#{ENV['GOOGLE_API_KEY']}" : nil %>
      <%= f.hidden_field :category, value: @place.types.join(",") if @place.types.present? %>
      <%= f.submit "投稿する" %>
    <% end %>
  <% end %>


</div>

app/views/places/search.html.erb
<div class="row">
  <div class="col-md-3">
    <h2>検索結果</h2>
    <%= form_with(url: places_search_path, method: :get, id: 'filter-search_form') do |f| %>
      <%= f.text_field :name, value: params[:name], placeholder: '遊び場名を入力してください' %>
      <%= f.label :types, 'カテゴリー' %>
      <%= f.select :types, options_for_select([['どこに遊びに？', nil], ['公園', 'park'], ['動物園', 'zoo'], ['観光名所', 'tourist_attraction'], ['遊園地', 'amusement_park'], ['水族館', 'aquarium'], ['美術館', 'art_gallery'], ['書店', 'book_store'], ['ボウリング場', 'bowling_alley'], ['カフェ', 'cafe'], ['キャンプ場', 'campground'], ['デパート', 'department_store'], ['図書館', 'library'], ['映画館', 'movie_theater'], ['博物館', 'museum'], ['ペットショップ', 'pet_store'], ['学校', 'school'], ['レストラン', 'restaurant'], ['ショッピングモール', 'shopping_mall'], ['スタジアム', 'stadium'], ['店舗', 'store']],selected: params[:types])  %>
      <p id="error-text">検索したい周辺の位置に<br>ピンをさしてください</p>
      <div class="d-flex">
        <label for="pin-coordinates-lat">緯度:</label>
        <div id="pin-coordinates-lat"></div> <!-- ピンの緯度を表示する要素 -->
      </div>
      <div class="d-flex">
        <label for="pin-coordinates-lng">経度:</label>
        <div id="pin-coordinates-lng"></div> <!-- ピンの経度を表示する要素 -->
      </div>
      <%= f.label :radius, '検索範囲:' %>
      <%= f.select :radius, options_for_select([['どこまで遠くに？', nil], ['1Km','1000'], ['5Km','5000'], ['10Km','10000'], ['30Km','30000']], selected: params[:radius]) %>
      <%= f.hidden_field :lat, value: params[:lat], id: 'lat' %>
      <%= f.hidden_field :lng, value: params[:lng], id: 'lng' %>
      
      <%= f.submit '検索', id: "submit_button" %>
      <%= button_tag '条件リセット', type: 'button', id: "condition_reset_button" %>
    <% end %>
    <input id="address" type="textbox" placeholder="場所を入力してください" >
    <input type="button" value="探す" onclick="codeAddress()">
    <div id="map"></div>
    
    <style>
      #map {
        height: 250px;
        width: 250px;
      }
    </style>
    
    <script>
      let map;
      let marker;
      let geocoder;
      // 三項演算子でlat!==""でtrueなら左falseなら右の値を変数に入れる
      let lat = getParam("lat") !== "" ? Number(getParam("lat")) : 35.155396 
      let lng = getParam("lng") !== "" ? Number(getParam("lng")) : 136.918969
      
      /*条件リセット*/
      document.getElementById('condition_reset_button').addEventListener('click', function() {
        document.getElementById('name').value = ""; // 名前フィールドの値を空にする
        let typesSelect = document.getElementById("types");
        typesSelect.selectedIndex = 0; // カテゴリーセレクトボックスを初期値に戻す
        let radiusSelect = document.getElementById("radius");
        radiusSelect.selectedIndex = 0; // 検索範囲セレクトボックスを初期値に戻す
        document.getElementById("pin-coordinates-lat").textContent = ""; // ピンの緯度を空にする
        document.getElementById("pin-coordinates-lng").textContent = ""; // ピンの経度を空にする
        if (marker) {
          marker.setMap(null); // ピンを地図上から削除する
        }
      });
      
      // javascriptでパラメーターを受取るための記述
      function getParam(name, url) {
        if (!url) url = window.location.href;
        name = name.replace(/[\[\]]/g, "\\$&");
        var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
            results = regex.exec(url);
        if (!results) return null;
        if (!results[2]) return '';
        return decodeURIComponent(results[2].replace(/\+/g, " "));
      }
      
      function initMap() {
        geocoder = new google.maps.Geocoder();
        // 緯度経度を表示させる
        function displayPinCoordinates(lat, lng) {
          document.getElementById("pin-coordinates-lat").textContent = lat;
          document.getElementById("pin-coordinates-lng").textContent = lng;
        }
        // params[:lat]の値が存在する場合の処理
        if (lat !== 35.155396) {
          console.log('params[:lat]の値が存在します');
          displayPinCoordinates(lat,lng)
        }
        map = new google.maps.Map(document.getElementById("map"), {
          center: { lat: lat, lng: lng },
          zoom: 10,
        });
        // デフォルトのピンを設定
        marker = new google.maps.Marker({
          position: { lat: lat, lng: lng },
          map: map,
          draggable: true
        });
        google.maps.event.addListener(map, "click", function(event) {
          //マーカーが複数できないようにする
          if (marker) {
            marker.setMap(null); 
          }
          marker = new google.maps.Marker({
            position: event.latLng,
            map: map,
            draggable: true,
          });
          document.getElementById("lat").value = event.latLng.lat();
          document.getElementById("lng").value = event.latLng.lng();
          displayPinCoordinates(event.latLng.lat(), event.latLng.lng()); // ピンの緯度経度を表示
          google.maps.event.addListener(marker, "dragend", function(event) {
            document.getElementById("lat").value = this.getPosition().lat();
            document.getElementById("lng").value = this.getPosition().lng();
            displayPinCoordinates(this.getPosition().lat(), this.getPosition().lng()); // ピンの緯度経度を表示
          });
        });
      }
      // 場所検索時の挙動
      function codeAddress() {
        let inputAddress = document.getElementById("address").value;
        geocoder.geocode({ address: inputAddress }, function(results, status) {
          if (status == "OK") {
            if (marker) {
              marker.setMap(null);
            }
            map.setCenter(results[0].geometry.location);
            marker = new google.maps.Marker({
              position: results[0].geometry.location,
              map: map,
              draggable: true,
            });
            document.getElementById("lat").value = results[0].geometry.location.lat();
            document.getElementById("lng").value = results[0].geometry.location.lng();
            displayPinCoordinates(results[0].geometry.location.lat(), results[0].geometry.location.lng()); // ピンの緯度経度を表示
            google.maps.event.addListener(marker, "dragend", function(event) {
              document.getElementById("lat").value = this.getPosition().lat();
              document.getElementById("lng").value = this.getPosition().lng();
              displayPinCoordinates(this.getPosition().lat(), this.getPosition().lng()); // ピンの緯度経度を表示
            });
          } else {}
        });
      }
      
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap" async defer></script>
  </div>
  <!--検索リザルト結果-->
  <div class="col-md-9">
    <%= render partial: 'search_results', locals: { places: @places } %>
  </div>
</div>