config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"

  # public ルーティング
  scope module: :public do
    get "homes/about" => "homes#about"
    resource :customers, only: [:show, :edit, :update] do
      collection do
        get 'check'
        patch 'withdrawal'
        get 'favorites'
        get 'comments'
      end
    end

    get "places/search", to: "places#search", as: "places_search"
    get "places/detailed_search", to: "places#detailed_search", as: "places_detailed_search"

    resources :playgrounds, only: [:create, :show]

    resources :posts, only: [:index, :show, :edit, :update, :new, :create, :destroy] do
      resources :post_comments, only: [:create, :destroy, :edit, :update]
      resource :post_favorites, only: [:create, :destroy]
    end
  end

  # admin ルーティング
  namespace :admin do
    get "homes/top" => "homes#top"
    resources :tags, except: [:show, :new]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
    resources :post_comments, only: [:index, :destroy]
  end

  # devise customer ルーティング
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_scope :customer do
    post "public/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # devise admin ルーティング
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
end

app/views/layouts/_error.html.erb
<!--エラーメッセージ(モデルとカラム指定)-->
<% if model.object.errors.any? %>
  <div class="alert col-12 m-0 ml-2 p-0">
    <ul class="list-unstyled my-auto">
      <% model.object.errors.full_messages_for(attribute).each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<!-- ビュー内でフラッシュメッセージを表示 -->
<!--色: success=緑,info=青,warning=オレンジ,error=赤-->
<% if flash.any? %>
  <script type="text/javascript">
    <% flash.each do |type, msg| %>
      <% toastr_type = case type
                       when "notice" then "info"
                       when "alert" then "error"
                       when "error" then "error"
                       when "success" then "success"
                       when "info" then "info"
                       when "warning" then "warning"
                       else type
                       end %>
      toastr['<%= toastr_type %>']('<%= msg %>');
    <% end %>
  </script>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row mt-2 mx-3 mx-sm-2">
      <div class="col-md-4 my-auto">
        <%= link_to root_path, data: {"turbolinks"=>false} do %>
          <div class="d-flex align-items-center logo">
            <div>
              <%= image_tag 'logo.not.name.png', size: '65x65', class: 'logo-image' %>
            </div>
            <div class="ml-2 mt-2">
              <h5 class="mb-0 mb-md-3">ChildrenPG</h5>
              <p style="font-size: 1rem;">遊び場検索・保存サイト</p>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-md-8 mt-2">
        <div class="row">
          <!--会員ログイン後ヘッダー-->
          <% if customer_signed_in? %>
            <div class="col-sm">
              <ul class="list-unstyled">
                <h3>初めての方へ</h3>
                <li><%= link_to "サイト説明", homes_about_path %></li>
                <li><%= link_to "ログアウトする",destroy_customer_session_path, method: :delete %></li>
              </ul>
            </div>
            <div class="col-sm">
              <ul class="list-unstyled">
                <h3>サイトマップ</h3>
                <li><%= link_to "遊び場を探す", root_path, data: {"turbolinks"=>false} %></li>
                <li><%= link_to "皆の投稿を見る", posts_path %></li>
                <li><%= link_to "マイページ",customers_path %></li>
                <li><%= link_to "いいねした投稿を見る", favorites_customers_path(customer_id: current_customer.id) %></li>
              </ul>
            </div>
            <div class="col-sm">
              <ul class="list-unstyled">
                <h3>SNS</h3>
                <li><a href="#"><i class="fab fa-facebook"></i> Facebook</a></li>
                <li><a href="#"><i class="fab fa-twitter"></i> Twitter</a></li>
                <li><a href="#"><i class="fab fa-instagram"></i> Instagram</a></li>
              </ul>
            </div>
          <!--管理者ログイン後ヘッダー-->
          <% elsif admin_signed_in? %>
            <div class="col-sm">
              <ul class="list-unstyled">
                <h3>サイトマップ</h3>
                <li><%= link_to "データ推移を見る", admin_homes_top_path, data: {"turbolinks"=>false} %></li>
                <li><%= link_to "会員の投稿一覧を見る", admin_posts_path %></li>
                <li><%= link_to "会員一覧を見る", admin_customers_path %></li>
                <li><%= link_to "会員のコメント一覧を見る", admin_post_comments_path %></li>
                <li><%= link_to "投稿タグを管理する", admin_tags_path %></li>
                <li><%= link_to "ログアウトする",destroy_admin_session_path, method: :delete %></li>
              </ul>
            </div>
            <div class="col-sm">
              <ul class="list-unstyled">
                <h3>会員側サイト</h3>
                <li><%= link_to "サイト説明", homes_about_path %></li>
                <li><%= link_to "遊び場を探す", root_path, data: {"turbolinks"=>false} %></li>
                <li><%= link_to "皆の投稿を見る", posts_path %></li>
              </ul>
            </div>
            <div class="col-sm">
              <ul class="list-unstyled">
                <h3>SNS</h3>
                <li><a href="#"><i class="fab fa-facebook"></i> Facebook</a></li>
                <li><a href="#"><i class="fab fa-twitter"></i> Twitter</a></li>
                <li><a href="#"><i class="fab fa-instagram"></i> Instagram</a></li>
              </ul>
            </div>
          <!--共通ログイン前ヘッダー-->
          <% else %>
            <div class="col-sm">
              <ul class="list-unstyled">
                <h3>初めての方へ</h3>
                <li><%= link_to "サイト説明", homes_about_path %></li>
                <li><%= link_to "新規登録する", new_customer_registration_path %></li>
                <li><%= link_to "ログインする",new_customer_session_path %></li>
              </ul>
            </div>
            <div class="col-sm">
              <ul class="list-unstyled">
                <h3>サイトマップ</h3>
                <li><%= link_to "遊び場を探す", root_path, data: {"turbolinks"=>false} %></li>
                <li><%= link_to "皆の投稿を見る", posts_path %></li>
              </ul>
            </div>
            <div class="col-sm">
              <ul class="list-unstyled">
                <h3>SNS</h3>
                <li><a href="#"><i class="fab fa-facebook"></i> Facebook</a></li>
                <li><a href="#"><i class="fab fa-twitter"></i> Twitter</a></li>
                <li><a href="#"><i class="fab fa-instagram"></i> Instagram</a></li>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
      <!--トップに移動するボタン-->
      <span id="top_btn">
        <a href="#">
          <div class="top-btn">
            <i class="fa-regular fa-circle-up top-btn"></i>
          </div>
        </a>
      </span>
    </div>
    
    <hr class="my-0">
    <div class="text-center">
      <p class="my-2" style="font-size: 0.9rem;">&copy; 2023 ChildrenPG. All rights reserved.</p>
    </div>
  </div>
</footer>

<style>
  /*トップに移動するボタン*/
  .container {
    position: relative;
  }
  .top-btn {
    position: absolute;
    right: 8px;
    bottom: 20px;
    font-size: 3.8rem;
  }
  
  a {
    font-size: 0.9rem;
  }
  
  @media screen and (min-width:375px) and ( max-width:768px) {
    .logo-image {
      width: 45px;
      height: 45px;
    }
    .logo h5 {
      font-size: 1.1rem;
    }
    .logo p {
      font-size: 0.9rem;
    }
  }
</style>

<script>
  $(function() {
    var topBtn = $('#top_btn a');
    topBtn.hide();
    $(window).scroll(function() {
      var scrollHeight = $(document).height(); // ページの全体の高さ
      var scrollPosition = $(window).height() + $(window).scrollTop(); // 現在のスクロール位置 + ウィンドウの高さ
      
      if (scrollHeight - scrollPosition <= 100) {
        // ページの最下部に近づいたらトップに戻るボタンを表示
        topBtn.fadeIn(500);
      } else {
        // ページの最下部でない場合はトップに戻るボタンを非表示
        topBtn.fadeOut(200);
      }
    });

    topBtn.click(function () {
      $('body, html').animate({
        scrollTop: 0
      }, 500); // トップに戻る時間
      event.preventDefault();
    });
  });
</script>

app/views/layouts/_header.html.erb
<header>
  <!--ナビゲーションメニュー-->
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <div class="row">
        <%= link_to root_path, data: {"turbolinks"=>false} do %> <!--マップ表示エラーが出るためターボリンクスを切っている-->
          <%= image_tag 'logo.header.png', size: '130x76' ,class: 'logo-image' %>
        <% end %>
        <%= link_to  "～遊び場検索・保存サイト～",homes_about_path, class: 'about' %>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="row collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <!--会員ログイン後ヘッダー-->
          <% if customer_signed_in? %>
            <li class="nav-item">
              <%= link_to "遊び場を探す", root_path, class: 'nav-link btn btn-light', data: {"turbolinks"=>false} %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", posts_path, class: 'nav-link btn btn-light ml-lg-2 mt-1 mt-lg-0' %>
            </li>
            <li class="nav-item">
              <%= link_to "マイページ",customers_path, class: 'nav-link btn btn-light ml-lg-2 mt-1 mt-lg-0' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト",destroy_customer_session_path, method: :delete, class: 'nav-link btn btn-light ml-lg-2 mt-1 mt-lg-0' %>
            </li>
          
          <!--管理者ログイン後ヘッダー-->
          <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "データ推移", admin_homes_top_path, class: 'nav-link btn btn-light ml-lg-5', data: {"turbolinks"=>false} %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", admin_posts_path, class: 'nav-link btn btn-light ml-lg-2 mt-1 mt-lg-0' %>
            </li>
            <li class="nav-item">
              <%= link_to "会員一覧", admin_customers_path, class: 'nav-link btn btn-light ml-lg-2 mt-1 mt-lg-0' %>
            </li>
            <li class="nav-item">
              <%= link_to "コメント一覧", admin_post_comments_path, class: 'nav-link btn btn-light ml-lg-2 mt-1 mt-lg-0' %>
            </li>
            <li class="nav-item">
              <%= link_to "タグ一覧", admin_tags_path, class: 'nav-link btn btn-light ml-lg-2 mt-1 mt-lg-0' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト",destroy_admin_session_path, method: :delete, class: 'nav-link btn btn-light ml-lg-2 mt-1 mt-lg-0' %>
            </li>
          
          <!--共通ログイン前ヘッダー-->
          <% else %>
            <li class="nav-item">
              <%= link_to "遊び場を探す", root_path, class: 'nav-link btn btn-light ml-lg-5', data: {"turbolinks"=>false} %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", posts_path, class: 'nav-link btn btn-light ml-lg-2 mt-1 mt-lg-0' %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link btn btn-light ml-lg-2 mt-1 mt-lg-0' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン",new_customer_session_path, class: 'nav-link btn btn-light ml-lg-2 mt-1 mt-lg-0' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

<style>
  @media screen and (min-width:375px) and ( max-width:768px) {
    header .logo-image {
      width: 108px;
      height: 62px;
    }
    
    header .about {
      font-size: 1rem;
      margin-top: 32px;
    }
  }
  
  @media screen and (min-width:768px) {
    header .about {
      font-size: 1.2rem;
      margin-top: 40px;
    }
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChildrenPG</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!--Googlefont読み込み-->
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet">
    
    <script src="https://kit.fontawesome.com/f11a1f82a2.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/flash' %>
    <%= render 'layouts/header' %>
    
    <main>
      <div class="main py-3">
        <%= yield %>
      </div>
    </main>
    
    <%= render 'layouts/footer' %>
    
  </body>
</html>